### ISSUE TITLE
Error when trying to edit body

### ISSUE THREAD

**Issue by jamrizzi** [kelsin/kapit#2]
I get the following error when trying to edit the body (aka when I hit the 'b' key)

```
TypeError: "options" argument must be an object───────────────────────────────────────────────────────────┐
    at normalizeSpawnArguments (child_process.js:398:11)                                                  │
    at exports.spawn (child_process.js:496:38)────────────────────────────────────────────────────────────┘
    at Screen.spawn (/home/jamrizzi/Projects/kapit/node_modules/blessed/lib/widget.js:1550:8)─────────────┐
    at Screen.exec (/home/jamrizzi/Projects/kapit/node_modules/blessed/lib/widget.js:1561:17)             │
    at Screen.tryCatcher (/home/jamrizzi/Projects/kapit/node_modules/bluebird/js/main/util.js:26:23)      │
    at Screen.ret [as execAsync] (eval at makeNodePromisifiedEval (/home/jamrizzi/Projects/kapit/node_modules/bluebird/js/main/promisify.js:163:12), <anonymous>:14:23)                                              │
    at /home/jamrizzi/Projects/kapit/lib/edit.js:24:21│                                                   │
    at tryCatcher (/home/jamrizzi/Projects/kapit/node_modules/bluebird/js/main/util.js:26:23)             │
    at Promise._settlePromiseFromHandler (/home/jamrizzi/Projects/kapit/node_modules/bluebird/js/main/promise.js:510:31)                                       │ │                                                   │
    at Promise._settlePromiseAt (/home/jamrizzi/Projects/kapit/node_modules/bluebird/js/main/promise.js:584:18)                                                │ │                                                   │
    at Async._drainQueue (/home/jamrizzi/Projects/kapit/node_modules/bluebird/js/main/async.js:128:12)    │
    at Async._drainQueues (/home/jamrizzi/Projects/kapit/node_modules/bluebird/js/main/async.js:133:10)   │
    at Immediate.Async.drainQueues (/home/jamrizzi/Projects/kapit/node_modules/bluebird/js/main/async.js:15:14)                                                │ │                                                   │
    at runCallback (timers.js:789:20)               │ │                                                   │
    at tryOnImmediate (timers.js:751:5)             │ │                                                   │
    at processImmediate [as _immediateCallback] (timers.js:722:5)                                         │
Unhandled rejection TypeError: "options" argument must be an object                                       │
    at normalizeSpawnArguments (child_process.js:398:11)                                                  │
    at exports.spawn (child_process.js:496:38)      │ │                                                   │
    at Screen.spawn (/home/jamrizzi/Projects/kapit/node_modules/blessed/lib/widget.js:1550:8)             │
    at Screen.exec (/home/jamrizzi/Projects/kapit/node_modules/blessed/lib/widget.js:1561:17)             │
    at Screen.tryCatcher (/home/jamrizzi/Projects/kapit/node_modules/bluebird/js/main/util.js:26:23)      │
    at Screen.ret [as execAsync] (eval at makeNodePromisifiedEval (/home/jamrizzi/Projects/kapit/node_modules/bluebird/js/main/promisify.js:163:12), <anonymous>:14:23)                                              │
    at /home/jamrizzi/Projects/kapit/lib/edit.js:24:21│                                                   │
    at tryCatcher (/home/jamrizzi/Projects/kapit/node_modules/bluebird/js/main/util.js:26:23)             │
    at Promise._settlePromiseFromHandler (/home/jamrizzi/Projects/kapit/node_modules/bluebird/js/main/promise.js:510:31)                                       │ │                                                   │
    at Promise._settlePromiseAt (/home/jamrizzi/Projects/kapit/node_modules/bluebird/js/main/promise.js:584:18)                                                │ │                                                   │
    at Async._drainQueue (/home/jamrizzi/Projects/kapit/node_modules/bluebird/js/main/async.js:128:12)    │
    at Async._drainQueues (/home/jamrizzi/Projects/kapit/node_modules/bluebird/js/main/async.js:133:10)   │
    at Immediate.Async.drainQueues (/home/jamrizzi/Projects/kapit/node_modules/bluebird/js/main/async.js:15:14)                                                │ │                                                   │
    at runCallback (timers.js:789:20)               │ │                                                   │
    at tryOnImmediate (timers.js:751:5)             │ │                                                   │
    at processImmediate [as _immediateCallback] (timers.js:722:5)                                         │

```

**Comment by jamrizzi** [comment]
I did a bit of digging into this problem, and it appears that `options` is a function instead of an object. I also noticed that the options are not being set. I can fix this by explicitly setting the options to an empty object.
